### ISSUE TITLE
datasets_error

### ISSUE THREAD

**Issue by Amri95** [koen-aerts/ECG_ML#1]
Hi there, I am getting the ModuleNotFoundError: No module named 'datasets' in the notebook.
and I am using ubuntu. Can you please sugggest the solution.

with regards

**Comment by koen-aerts** [comment]
> Hi there, I am getting the ModuleNotFoundError: No module named 'datasets' in the notebook.
> and I am using ubuntu. Can you please sugggest the solution.
> 
> with regards

Hi, you need to download the directories "datasets" and "utils" from the mitdb project at https://github.com/Nospoko/qrs-tutorial . Place them in the same directory where your notebooks are.
